package com.fiap.hackaton.infrastructure.config.db.schema;

import com.fiap.hackaton.entity.colaborador.model.Colaborador;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.UUID;

@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "colaborador")
public class ColaboradorSchema {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(unique = true, nullable = false, name = "cpf")
    private String cpf;

    @Column(nullable = false, name = "nome")
    private String nome;

    @Column(unique = true, nullable = false, name = "matricula'")
    private String matricula;

    @Column(nullable = false, name = "primeiro_dia_cadastro'")
    private LocalDateTime primeiroDiaCadastro;

    @Column(nullable = false, name = "cep'")
    private String cep;

    @Column(nullable = false, name = "numero_casa'")
    private Integer numeroCasa;

    @ManyToOne
    @JoinColumn(name = "hospital_id", nullable = false)
    private HospitalSchema hospital;

    @Column(nullable = false, name = "setor'")
    private String setor;

    @Column(nullable = false, name = "ativo'")
    private Boolean ativo;

    public ColaboradorSchema(Colaborador colaborador) {
        this.cpf = colaborador.getCpf();
        this.nome = colaborador.getNome();
        this.matricula = colaborador.getMatricula();
        this.primeiroDiaCadastro = colaborador.getPrimeiroDiaCadastro();
        this.cep = colaborador.getCep();
        this.numeroCasa = colaborador.getNumeroCasa();
        this.hospital = new HospitalSchema(colaborador.getHospital());
        this.setor = colaborador.getSetor();
        this.ativo = colaborador.getAtivo();
    }

    public Colaborador toColaborador() {
        Colaborador colaborador = new Colaborador (
                this.cpf,
                this.nome,
                this.matricula,
                this.primeiroDiaCadastro,
                this.cep,
                this.numeroCasa,
                this.hospital.toHospital(),
                this.setor,
                this.ativo
        );

        colaborador.setId(this.id); // transform the schema id (generated by database) to entity customer id

        return colaborador;
    }

}