package com.fiap.hackaton.infrastructure.config.db.schema;

import com.fiap.hackaton.entity.hospital.model.Hospital;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "Hospital")
public class HospitalSchema extends AbstractEntitySchema<UUID> {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false, name = "cep")
    private String cep;

    @Column(nullable = false, name = "numero")
    private Integer numero;

    @OneToMany(mappedBy = "hospital", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<ColaboradorSchema> colaboradores = new ArrayList<>();

    public HospitalSchema(Hospital hospital) {
        this.cep = hospital.getCep();
        this.numero = hospital.getNumero();
        this.colaboradores = hospital.getColaboradores().stream()
                .map(ColaboradorSchema::new)
                .collect(Collectors.toList());
    }

    public Hospital toHospital() {
        Hospital hospital = new Hospital(
                this.getColaboradores().stream().map(ColaboradorSchema::toColaborador).collect(Collectors.toList()),
                this.getCep(),
                this.getNumero()
        );

        hospital.setId(this.getId()); // transform the schema id (generated by database) to entity customer id

        return hospital;
    }
}